\version "2.24.0"

\header {
  title = "7099892f-2b38-41fb-9813-ea8055cbc385"
  composer = "Guitar Tab Generator"
  tagline = "Generated by Guitar Tab Generator"
}

% Guitar tuning (high to low: e' b g d a, e,)
#(define guitar-tuning '(e' b g d a, e,))

% The music
music = \relative {
  \tempo 4 = 120
  \time 4/4
  r16 r32 g,16\6 g,16\6 g,32\6 g,16\6 a,8\5 a,32\5 a,2\5 c16\5 ^\markup{H} c32\5 d8\4 r2 r4 r8 e8\4 c16\5 c8\5 a,32\5 ^\markup{P} r1 r1 r1 r1 r2 r8 r32 a,32\5 r1 r4 r16 a,16\5 a,8\5
  \bar "|."
}

% Score with standard notation and tablature
\score {
  <<
    \new Staff {
      \clef "treble_8"
      \key c \major
      \music
    }
    \new TabStaff {
      \set TabStaff.stringTunings = #guitar-tuning
      \music
    }
  >>
  \layout {
    \context {
      \TabStaff
      \override TabNoteHead.font-size = #-2
      \override Stem.transparent = ##t
      \override Beam.transparent = ##t
    }
  }
  \midi { \tempo 4 = 120 }
}
